# -*- coding: utf-8 -*-
"""Assignments_DWDM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5ZuuA1jCvXFt2Sy0fYGzyXkiW6A58VO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/muhammad-mohsin-1/DWDM-Assignments/refs/heads/main/water_potability.csv"

df = pd.read_csv(url)

print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

print("Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicates:", df.duplicated().sum())
print("\nBasic Statistics:")
df.describe()

plt.figure(figsize=(10, 4))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis', yticklabels=False)
plt.title("Missing Values Heatmap")
plt.show()

df['ph'] = df['ph'].fillna(df['ph'].median())
df['Sulfate'] = df['Sulfate'].fillna(df['Sulfate'].median())
df['Trihalomethanes'] = df['Trihalomethanes'].fillna(df['Trihalomethanes'].median())

print("Missing values after handling:")
print(df.isnull().sum())

plt.figure(figsize=(15, 8))
df.boxplot()
plt.xticks(rotation=45)
plt.title("Boxplot - Outliers Detection")
plt.tight_layout()
plt.show()

cols = ['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate',
        'Conductivity', 'Organic_carbon', 'Trihalomethanes', 'Turbidity']

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

print("Shape after removing outliers:", df.shape)

df['ph_category'] = pd.cut(df['ph'],
                            bins=[0, 6.5, 8.5, 14],
                            labels=['Acidic', 'Neutral', 'Alkaline'])

print(df['ph_category'].value_counts())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['ph_category_encoded'] = le.fit_transform(df['ph_category'])

print(df[['ph_category', 'ph_category_encoded']].head(10))

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cols_to_scale = ['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate',
                 'Conductivity', 'Organic_carbon', 'Trihalomethanes', 'Turbidity']

df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

print("After Scaling:")
df[cols_to_scale].describe()

from sklearn.model_selection import train_test_split

X = df.drop(['Potability', 'ph_category'], axis=1)
y = df['Potability']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

df.to_csv('cleaned_water_potability.csv', index=False)
print("Cleaned dataset saved!")
print("Final Shape:", df.shape)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(n_estimators=100, random_state=42)

dt.fit(X_train, y_train)
rf.fit(X_train, y_train)

print("Models trained successfully!")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

dt_pred = dt.predict(X_test)
rf_pred = rf.predict(X_test)

print("Decision Tree:")
print("  Accuracy :", accuracy_score(y_test, dt_pred))
print("  Precision:", precision_score(y_test, dt_pred))
print("  Recall   :", recall_score(y_test, dt_pred))
print("  F1-Score :", f1_score(y_test, dt_pred))

print("\nRandom Forest:")
print("  Accuracy :", accuracy_score(y_test, rf_pred))
print("  Precision:", precision_score(y_test, rf_pred))
print("  Recall   :", recall_score(y_test, rf_pred))
print("  F1-Score :", f1_score(y_test, rf_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for ax, (name, pred) in zip(axes, [("Decision Tree", dt_pred), ("Random Forest", rf_pred)]):
    cm = confusion_matrix(y_test, pred)
    disp = ConfusionMatrixDisplay(cm)
    disp.plot(ax=ax, colorbar=False)
    ax.set_title(f'{name} - Confusion Matrix')

plt.tight_layout()
plt.show()

from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(8, 5))

for name, model in [("Decision Tree", dt), ("Random Forest", rf)]:
    y_prob = model.predict_proba(X_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    plt.plot(fpr, tpr, label=f'{name} (AUC = {auc(fpr, tpr):.2f})')

plt.plot([0,1], [0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

from sklearn.preprocessing import StandardScaler

scaler2 = StandardScaler()

cols_to_scale = ['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate',
                 'Conductivity', 'Organic_carbon', 'Trihalomethanes', 'Turbidity']

df_standard = df.copy()
df_standard[cols_to_scale] = scaler2.fit_transform(df[cols_to_scale])

print("After Standardization:")
df_standard[cols_to_scale].describe()

"""**Assignment_4 Start Here**"""

df_reg = pd.read_csv('cleaned_water_potability.csv')

X_reg = df_reg.drop(['Sulfate', 'Potability', 'ph_category', 'ph_category_encoded'], axis=1)
y_reg = df_reg['Sulfate']

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42)

print("X_train:", X_train_r.shape)
print("X_test:", X_test_r.shape)

plt.figure(figsize=(10, 8))
sns.heatmap(df_reg.select_dtypes(include=np.number).corr(),
            annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Feature Correlation Heatmap")
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

lr = LinearRegression()
dtr = DecisionTreeRegressor(random_state=42)
rfr = RandomForestRegressor(n_estimators=100, random_state=42)

lr.fit(X_train_r, y_train_r)
dtr.fit(X_train_r, y_train_r)
rfr.fit(X_train_r, y_train_r)

print("All 3 models trained successfully!")

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

for name, model in [("Linear Regression", lr),
                     ("Decision Tree", dtr),
                     ("Random Forest", rfr)]:
    y_pred = model.predict(X_test_r)
    rmse = np.sqrt(mean_squared_error(y_test_r, y_pred))
    mae = mean_absolute_error(y_test_r, y_pred)
    r2 = r2_score(y_test_r, y_pred)

    print(f"\n{name}:")
    print(f"  RMSE : {rmse:.4f}")
    print(f"  MAE  : {mae:.4f}")
    print(f"  R2   : {r2:.4f}")

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

for ax, (name, model) in zip(axes, [("Linear Regression", lr),
                                      ("Decision Tree", dtr),
                                      ("Random Forest", rfr)]):
    y_pred = model.predict(X_test_r)
    ax.scatter(y_test_r, y_pred, alpha=0.5, color='steelblue')
    ax.plot([y_test_r.min(), y_test_r.max()],
            [y_test_r.min(), y_test_r.max()], 'r--')
    ax.set_xlabel('Actual')
    ax.set_ylabel('Predicted')
    ax.set_title(name)

plt.tight_layout()
plt.show()